/**
 * Placeholder inventory data for static UX phase — not wired to Supabase.
 */

export const KPI_DATA = {
  totalSkus: 188,
  onHandUnits: 642,
  reservedUnits: 14,
  availableUnits: 628,
  lowStock: 9,
  unmappedLines: 3,
  inventoryIssues: 6,
  lastChannelSync: "12 min ago",
};

export const CHANNEL_STATUS = {
  kk: { label: "KK Store", connected: true, url: "karrykrazestore.com" },
  ebay: { label: "eBay", connected: true, url: "ebay.com/usr/karrykrazestore" },
  amazon: { label: "Amazon", connected: true, url: "US • Amazon.com" },
  lastGlobalSync: "June 3, 2026, 1:42 PM",
  live: true,
};

export const TAB_COUNTS = {
  all: 188,
  lowStock: 9,
  unmapped: 3,
  issues: 6,
};

export const ALERTS = [
  { id: "unmapped-order", label: "3 Unmapped Order Lines", tone: "violet" },
  { id: "negative-stock", label: "2 Negative Stock", tone: "orange" },
  { id: "ebay-ended", label: "1 eBay Listing Ended", tone: "purple" },
  { id: "amazon-inactive", label: "4 Amazon Inactive", tone: "yellow" },
  { id: "parcel-mapping", label: "5 Parcel Rows Awaiting Mapping", tone: "blue" },
];

export const FILTER_OPTIONS = {
  status: [
    { value: "", label: "All Statuses" },
    { value: "healthy", label: "Healthy" },
    { value: "low", label: "Low" },
    { value: "issue", label: "Issue" },
  ],
  channel: [
    { value: "", label: "All Channels" },
    { value: "kk", label: "KK Store" },
    { value: "ebay", label: "eBay" },
    { value: "amazon", label: "Amazon" },
    { value: "parcel", label: "Parcel Import" },
  ],
  inventoryState: [
    { value: "", label: "All States" },
    { value: "in_stock", label: "In Stock" },
    { value: "low", label: "Low Stock" },
    { value: "out", label: "Out of Stock" },
    { value: "negative", label: "Negative On Hand" },
    { value: "negative_available", label: "Negative Available" },
    { value: "reserved", label: "Has Reserved" },
  ],
  category: [
    { value: "", label: "All Categories" },
    { value: "headwear", label: "Headwear" },
    { value: "bags", label: "Bags" },
    { value: "keychains", label: "Keychains" },
    { value: "accessories", label: "Accessories" },
  ],
  syncState: [
    { value: "", label: "All Sync States" },
    { value: "synced", label: "Synced" },
    { value: "mismatch", label: "Mismatch" },
    { value: "stale", label: "Stale" },
    { value: "never", label: "Never Synced" },
  ],
  issueType: [
    { value: "", label: "All Issue Types" },
    { value: "unmapped_order_line", label: "Unmapped Order Line" },
    { value: "negative_stock", label: "Negative Stock" },
    { value: "negative_available", label: "Negative Available" },
    { value: "ebay_qty_cache_missing", label: "eBay Qty Cache Missing" },
    { value: "ebay_unsupported_variation", label: "eBay Unsupported Variation" },
    { value: "channel_sync_failed", label: "Channel Sync Failed" },
    { value: "ebay_listing_ended", label: "eBay Listing Ended" },
    { value: "amazon_listing_inactive", label: "Amazon Inactive" },
    { value: "parcel_mapping_missing", label: "Parcel Mapping Missing" },
  ],
  sortBy: [
    { value: "updated_desc", label: "Last Updated (Newest)" },
    { value: "title_asc", label: "Title A–Z" },
    { value: "title_desc", label: "Title Z–A" },
    { value: "available_asc", label: "Available Low–High" },
    { value: "available_desc", label: "Available High–Low" },
  ],
};

/** @typedef {'healthy'|'low'|'issue'} InventoryStatus */
/** @typedef {'all'|'lowStock'|'unmapped'|'issues'} InventoryTab */

/**
 * @typedef {Object} InventoryRow
 * @property {string} id
 * @property {string} title
 * @property {string} variant
 * @property {string} [variantDetail]
 * @property {string} [shortSku]
 * @property {string} [thumbClass]
 * @property {string} [imageUrl]
 * @property {string} internalSku
 * @property {number|null} kkStock
 * @property {number|null} ebayStock
 * @property {number|null} amazonStock
 * @property {number} onHand
 * @property {number} reserved
 * @property {number} available
 * @property {number} threshold
 * @property {InventoryStatus} status
 * @property {string} updated
 * @property {string} category
 * @property {boolean} unmapped
 * @property {boolean} hasIssue
 * @property {string[]} issueTypes
 * @property {'synced'|'mismatch'|'stale'|'never'} syncState
 */

/** @type {InventoryRow[]} */
export const INVENTORY_ROWS = [
  {
    id: "inv-001",
    title: "Ribbed Knit Earflap Beanie",
    variant: "Pink",
    variantDetail: "Pink • Adult",
    shortSku: "KK-0001",
    thumbClass: "bg-pink-100",
    internalSku: "KK-0001-PNK-AD",
    kkStock: 38,
    ebayStock: 38,
    amazonStock: 38,
    onHand: 38,
    reserved: 2,
    available: 36,
    threshold: 10,
    status: "healthy",
    updated: "2 min ago",
    category: "headwear",
    unmapped: false,
    hasIssue: false,
    issueTypes: [],
    syncState: "synced",
  },
  {
    id: "inv-002",
    title: "Puffy Heart Bag Charm",
    variant: "Red",
    variantDetail: "Red • One Size",
    shortSku: "KK-0002",
    thumbClass: "bg-red-100",
    internalSku: "KK-0002-RED-OS",
    kkStock: 8,
    ebayStock: 8,
    amazonStock: 7,
    onHand: 8,
    reserved: 1,
    available: 7,
    threshold: 12,
    status: "low",
    updated: "8 min ago",
    category: "bags",
    unmapped: false,
    hasIssue: true,
    issueTypes: ["amazon_listing_inactive"],
    syncState: "mismatch",
  },
  {
    id: "inv-003",
    title: "Star Keychain",
    variant: "Gold",
    variantDetail: "Gold • One Size",
    shortSku: "KK-0003",
    thumbClass: "bg-amber-100",
    internalSku: "KK-0003-GLD-OS",
    kkStock: 40,
    ebayStock: 40,
    amazonStock: 41,
    onHand: 40,
    reserved: 0,
    available: 40,
    threshold: 8,
    status: "healthy",
    updated: "12 min ago",
    category: "keychains",
    unmapped: false,
    hasIssue: true,
    issueTypes: [],
    syncState: "mismatch",
  },
  {
    id: "inv-004",
    title: "Bow Beanie",
    variant: "Black",
    variantDetail: "Black • Adult",
    shortSku: "KK-0004",
    thumbClass: "bg-gray-200",
    internalSku: "KK-0004-BLK-AD",
    kkStock: 22,
    ebayStock: 22,
    amazonStock: 22,
    onHand: 22,
    reserved: 3,
    available: 19,
    threshold: 10,
    status: "healthy",
    updated: "18 min ago",
    category: "headwear",
    unmapped: false,
    hasIssue: false,
    issueTypes: [],
    syncState: "synced",
  },
  {
    id: "inv-005",
    title: "Checkered Lanyard",
    variant: "Pink/White",
    variantDetail: "Pink/White • One Size",
    shortSku: "KK-0005",
    thumbClass: "bg-kkpeach/80",
    internalSku: "KK-0005-PKW-OS",
    kkStock: 5,
    ebayStock: 5,
    amazonStock: 5,
    onHand: 5,
    reserved: 0,
    available: 5,
    threshold: 15,
    status: "low",
    updated: "25 min ago",
    category: "accessories",
    unmapped: false,
    hasIssue: false,
    issueTypes: [],
    syncState: "synced",
  },
  {
    id: "inv-006",
    title: "Ribbed Knit Earflap Beanie",
    variant: "Cream",
    variantDetail: "Cream • Adult",
    shortSku: "KK-0001",
    thumbClass: "bg-stone-100",
    internalSku: "KK-0001-CRM-AD",
    kkStock: 38,
    ebayStock: 40,
    amazonStock: 38,
    onHand: 38,
    reserved: 0,
    available: 38,
    threshold: 10,
    status: "issue",
    updated: "31 min ago",
    category: "headwear",
    unmapped: false,
    hasIssue: true,
    issueTypes: [],
    syncState: "mismatch",
  },
  {
    id: "inv-007",
    title: "Brass D Ring x3",
    variant: "Gold",
    variantDetail: "Gold • 3-Pack",
    shortSku: "KK-0044",
    thumbClass: "bg-yellow-100",
    internalSku: "KK-0044-GLD-3PK",
    kkStock: -2,
    ebayStock: 0,
    amazonStock: null,
    onHand: -2,
    reserved: 0,
    available: -2,
    threshold: 5,
    status: "issue",
    updated: "45 min ago",
    category: "accessories",
    unmapped: true,
    hasIssue: true,
    issueTypes: ["negative_stock", "ebay_listing_ended"],
    syncState: "mismatch",
  },
  {
    id: "inv-008",
    title: "Puffy Heart Bag Charm",
    variant: "Pink",
    variantDetail: "Pink • One Size",
    shortSku: "KK-0002",
    thumbClass: "bg-pink-50",
    internalSku: "KK-0002-PNK-OS",
    kkStock: 14,
    ebayStock: 14,
    amazonStock: 14,
    onHand: 14,
    reserved: 4,
    available: 10,
    threshold: 12,
    status: "low",
    updated: "1 hr ago",
    category: "bags",
    unmapped: false,
    hasIssue: false,
    issueTypes: [],
    syncState: "synced",
  },
  {
    id: "inv-009",
    title: "Star Keychain",
    variant: "Silver",
    variantDetail: "Silver • One Size",
    shortSku: "KK-0003",
    thumbClass: "bg-slate-100",
    internalSku: "KK-0003-SLV-OS",
    kkStock: null,
    ebayStock: null,
    amazonStock: null,
    onHand: 0,
    reserved: 0,
    available: 0,
    threshold: 8,
    status: "issue",
    updated: "2 hr ago",
    category: "keychains",
    unmapped: true,
    hasIssue: true,
    issueTypes: ["unmapped_order_line", "parcel_mapping_missing"],
    syncState: "never",
  },
  {
    id: "inv-010",
    title: "Bow Beanie",
    variant: "White",
    variantDetail: "White • Adult",
    shortSku: "KK-0004",
    thumbClass: "bg-gray-50",
    internalSku: "KK-0004-WHT-AD",
    kkStock: 16,
    ebayStock: 16,
    amazonStock: 15,
    onHand: 16,
    reserved: 2,
    available: 14,
    threshold: 10,
    status: "healthy",
    updated: "3 hr ago",
    category: "headwear",
    unmapped: false,
    hasIssue: true,
    issueTypes: ["amazon_listing_inactive"],
    syncState: "stale",
  },
];

export const LEDGER_ENTRIES = [
  {
    id: "led-001",
    time: "Today 2:12 PM",
    product: "Ribbed Knit Earflap Beanie · Pink",
    change: "+25",
    reason: "Parcel Receive",
    source: "Parcel Import",
    reference: "BST-2026-0188",
  },
  {
    id: "led-002",
    time: "Today 1:48 PM",
    product: "Bow Beanie · Black",
    change: "-2",
    reason: "KK Paid Order Reserve",
    source: "KK Store",
    reference: "KK-ORD-88421",
  },
  {
    id: "led-003",
    time: "Today 12:30 PM",
    product: "Star Keychain · Gold",
    change: "-1",
    reason: "eBay Shipment",
    source: "eBay",
    reference: "EBY-18-99201",
  },
  {
    id: "led-004",
    time: "Today 11:05 AM",
    product: "Puffy Heart Bag Charm · Red",
    change: "-1",
    reason: "Amazon Order",
    source: "Amazon",
    reference: "AMZ-402-8812",
  },
  {
    id: "led-005",
    time: "Yesterday 4:22 PM",
    product: "Checkered Lanyard · Pink/White",
    change: "+12",
    reason: "Parcel Receive",
    source: "Parcel Import",
    reference: "BST-2026-0182",
  },
  {
    id: "led-006",
    time: "Yesterday 2:10 PM",
    product: "Brass D Ring x3 · Gold",
    change: "-3",
    reason: "Manual Adjustment",
    source: "Admin",
    reference: "ADJ-2026-0044",
  },
];

export const INVENTORY_ISSUES = [
  {
    id: "iss-001",
    type: "unmapped_order_line",
    label: "Unmapped Order Line",
    severity: "high",
    description: "Paid order lines with no internal SKU mapping — stock not deducted.",
    affectedCount: 3,
  },
  {
    id: "iss-002",
    type: "negative_stock",
    label: "Negative Stock",
    severity: "critical",
    description: "On-hand quantity below zero — fulfillment may exceed physical stock.",
    affectedCount: 2,
  },
  {
    id: "iss-003",
    type: "ebay_listing_ended",
    label: "eBay Listing Ended",
    severity: "medium",
    description: "eBay listing ended at zero qty — restock may require relist flow.",
    affectedCount: 1,
  },
  {
    id: "iss-004",
    type: "amazon_listing_inactive",
    label: "Amazon Listing Inactive",
    severity: "medium",
    description: "Amazon listing inactive due to zero or suppressed inventory.",
    affectedCount: 4,
  },
  {
    id: "iss-005",
    type: "parcel_mapping_missing",
    label: "Parcel Mapping Missing",
    severity: "high",
    description: "Approved parcel rows not mapped to KK products — stock not received.",
    affectedCount: 5,
  },
];
